- name: nginx installattion
  hosts: frontend
  become: yes
  tasks:
  - name: nginx installation
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: enable and start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes