- name: nginx installattion
  hosts: frontend
  become: yes
  tasks:
  - name: nginx installation
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: enable and start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: delete home directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent
  
  - name: create directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory